[[redirects]]
  from = "https://hypothesis-pattern-library.netlify.com/*"
  to = "https://hypothesis-pattern-library.netlify.com/"
  status = 200
[[headers]]
  for = "/serviceworker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"