[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/serviceworker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"